version: "3"

services:
  node:
    container_name: iheroes-server
    build: "."
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - mongodb
    networks:
      - app-connect
    ports:
      - "8000:8000"

  mongodb:
    container_name: iheroes-mongodb
    image: mongo
    restart: unless-stopped
    volumes:
    #   - postgres-tracking-data:/data/db
    - /home/Docker/Volumes/MongoDB:/data/db
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - app-connect

volumes:
  postgres-tracking-data:

networks:
  app-connect:
    driver: bridge